spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service1
          uri: http://localhost:8089/
          predicates:
            - Path=/service1/**
        - id: service2
          uri: http://localhost:8090/
          predicates:
            - Path=/service2/**
        - id: auth_server
          uri: http://localhost:8091/
          predicates:
            - Path=/**

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    preferIpAddress: true


